name: portals_flutter
description: A package offering a beautiful extensible UI for using portals.
version: 0.0.1
homepage: https://github.com/marcelgarus/portals

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  portals: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
